let string ='EJEMPLO DE UNA CADENA PLO';
let index = string.indexOf('A');
console.log(index);
console.log(string.indexOf('PLO'));
console.log(string.indexOf('DEN'));
console.log(string.indexOf('UNA'));
console.log(string.indexOf('EM'));
console.log(string.indexOf('  '));
console.log(string.lastIndexOf('PLO'));
console.log(string.lastIndexOf('DE'));
console.log(string.lastIndexOf('E'));